version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    image: frontend-dev
    restart: always
    container_name: frontend-dev
    volumes:
      - ./apps/frontend/src:/usr/src/app/apps/frontend/src:ro
    networks:
      - mynetwork

  nginx:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.dev
    image: nginx-dev
    restart: always
    depends_on:
      - frontend
    ports:
      - 3000:80
      - 443:443
    container_name: nginx-dev
    networks:
      - mynetwork

networks:
  mynetwork:
