version: "3.9"

services:
  nginx:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.prod
    image: nginx-prod
    container_name: nginx-prod
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - mynetwork

networks:
  mynetwork:
